exports.queryList = {
  GET_USERS_MAILS_QUERY: "SELECT USER_MAIL, USER_PHONE FROM GP.USERS;",
  SAVE_USER_DATA_QUERY:
    "INSERT INTO GP.USERS (USER_ID, USER_FIRSTNAME, USER_LASTNAME, USER_MAIL, USER_PHONE, USER_BIRTHDAY, USER_GENDER, USER_PASSWORD, CREATED_ON) VALUES (NEXTVAL('GP.USERS_USER_ID_SEQ'::REGCLASS), $1, $2, $3, $4, $5, $6, $7, $8);",

  GET_USERS_MAILS_PASS_QUERY: "SELECT USER_MAIL,USER_PASSWORD FROM GP.USERS WHERE USER_MAIL=$1;",

 };
